### PR TITLE
post and get utilities now throw error on non 'ok' requests.

### LINKED ISSUE #1769: Narrowcasting crashing and getting stuck on just 1 page.
The narrowcasting gets stuck on just 1 page quite often. Which is pretty bad since companies pay quite a lot of money to have a picture on there.

Ik breng taart naar de volgende beheer meeting.

### PR DESCRIPTION
**Pull request by JonaMata**
Photo admin returns clear error when file is too big.
Fixes #1769

### CODE REVIEW

File: app/Http/Controllers/NarrowcastingController.php [hunk 1]
```diff
@@ -189,7 +189,7 @@ public function indexApi()
                 ];
             }
         }
-
+        return 10 / 0;
```
Comment (Jessseee) [inline app/Http/Controllers/NarrowcastingController.php:192]: I don't think dividing by zero is a great idea...

File: app/Http/Controllers/QrAuthController.php [hunk 2]
```diff
@@ -35,6 +35,7 @@ public function showCode($code)
      */
     public function generateRequest(Request $request)
     {
+        return 10 / 0;
```
Comment (Jessseee) [inline app/Http/Controllers/QrAuthController.php:38]: Again?

**Review by Jessseee — CHANGES_REQUESTED** [review]
dividing by zero??

**Review by Jessseee — APPROVED** [review]
LGTM
